### ISSUE TITLE
Plugin Initialization Issue: Shutdown After First Data Transmission and Configuration Handling Problems

### ISSUE THREAD

**Issue by kwitekrac** [fledge-power/fledge-north-iec104#57]
**Describe the bug**
I am encountering an issue with the initialization of the IEC104North plugin. The primary problem is that the plugin shuts down after the first data transmission. However, after a restart—or if the restart occurs before any data is sent—the plugin operates correctly.

**To Reproduce**
Here is the sequence of actions I followed:
1. Start Fledge and enable the IEC104North plugin in the script importModules.sh:
```bash
# Create service north 
curl -sX POST http://localhost:8081/fledge/service -d '{"name":"'$n1_north_service_name'","type":"north","plugin":"iec104","enabled":true}'
```

2. With Fledge running, I update the plugin configuration (specifically, exchanged_data), which is recognized and processed by Fledge
3. I then run a test script that sends data to the south plugins. (Note: The assets do not exist before this operation.)
Upon running the test, the following error occurs for each asset:
```
Fledge iec104north[1493]: ERROR: iec104 - IEC104Server::send - Data point 1:6 not found or type M_ME_NC_1 (13) not expected
```
followed by the log message:
```
Fledge iec104north[1493]: INFO: iec104 - plugin_shutdown - Shutting down the plugin...
```

Upon deeper investigation, I found that logs from the plugin initialization, such as:
_plugin.cpp_
```cpp
std::string beforeLog = Iec104PivotUtility::PluginName + " - plugin_init -";
Iec104PivotUtility::log_info("%s Initializing the plugin", beforeLog.c_str());
````
are missing. This absence of initialization logs suggests that the plugin initialization may not have been performed correctly.

The complete log is attached as a Word document, with my comments and important logs highlighted in color. Note that two filters are enabled in the IEC104North plugin pipeline: `to_pivot` and the standard `iec104_pivot_filter` - that's not a mistake.

**Expected behavior**
A plugin should handle its configuration properly and be ready to send data afterward.

**System**
Fledge 2.5.0 dockerized under Ubuntu 20.04
[Fledge rsyslogd- iec104north plugin init.docx](https://github.com/user-attachments/files/16506436/Fledge.rsyslogd-.iec104north.plugin.init.docx)

**Comment by Aeredren** [comment]
@fledge-power/dev-equans can you take a look at this issue. Maybe the init process have been overlooked, and we might run into this bug if we send data too early ?

**Comment by FlorentP42** [comment]
@Aeredren We did not experience this in out automated tests so far, but maybe this state is not reachable for us as the importModules.sh we use enforce a Fledge restart as it is mandatory for newly created control pipelines to work.

A few points of interest here :  

- About some logs not being displayed, this is a known behavior due to the fact that plugins will start at WARN log level by default: even if you can enable lower log levels in the plugin options, some logs that happen very early in the plugin launch process will never be displayed because the plugin configuration has not yet been read at this point. I suggested a solution to ensure that all logs can be seen even at startup for debug purposes, but it was never implemented: https://github.com/fledge-power/fledge-north-iec104/issues/56
- About the issue you encountered, after the north plugin did shutdown, are you able to start it again, and is Fledge operating correctly afterward? Having something that does not work as intended, but does after a restart reminds me if this issue we raised a long time ago but was never totally solved that caused a complete hang of Fledge where it was still running but would not answer to any API call (can't seem to find back the ticket related to it sadly).

**Comment by kwitekrac** [comment]
@FlorentP42 @Aeredren 
 I repeated my test with a simple MQTT South plugin and an IEC104 North plugin, considering two scenarios:  

## Scenario 1
1. Start Fledge 2.5.0.
2. Set the log level to DEBUG and enable the plugin via the UI.
3. Configure the North plugin and the `exchanged_data` and `protocol_stack` filters using the REST API.
4. Send data to the South plugin for the first time—this creates a new asset that should be forwarded to IEC104.
5. Wait 1 minute and trigger a data change.  

Upon analyzing the logs, I noticed that after the configuration was changed via the REST API, the `plugin_shutdown` function was **not** triggered. Instead, it was only triggered when the South plugin received the first set of data.  

[Scenario 1 logs.docx](https://github.com/user-attachments/files/18110490/Scenario.1.logs.docx)

## Scenario 2
1. Start Fledge 2.5.0.
2. Send data to the South plugin for the first time—this creates a new asset.
3. Set the log level to DEBUG and enable the plugin via the UI.
4. Configure the North plugin and the `exchanged_data` and `protocol_stack` filters using the REST API.
5. Wait 1 minute and trigger a data change.  

In this scenario, after the configuration change in step 4, the `plugin_shutdown` function **was** triggered, and the data received in step 5 was forwarded correctly.  

[Scenario 2 logs.docx](https://github.com/user-attachments/files/18110498/Scenario.2.logs.docx)

## Key Observations
- The only difference between Scenario 1 and Scenario 2 is that, in Scenario 2, the South plugin had already received data and created an asset before configuring the North plugin.  
- In Scenario 2, after enabling the plugin from the UI, the North plugin attempted to forward previously received data stored in the asset. However, before the `exchanged_data` was configured, the following error was logged:  
  `'...Asset 'dev00000' not found in exchangedData'.`  

## Final Conclusion
If the IEC104 North plugin is configured **before any data is received by Fledge**, the plugin is not restarted, which causes issues with forwarding the first data set. The root cause of this behavior is currently unknown.  

## Workaround
To avoid this issue, ensure that data has already been received by Fledge before configuring the North plugin, or trigger a Fledge restart via the REST API after configuration.

**Comment by FlorentP42** [comment]
> The only difference between Scenario 1 and Scenario 2 is that, in Scenario 2, the South plugin had already received data and created an asset before configuring the North plugin.

Starting the south plugin that sends a copy of every known asset during its initialization phase before starting the north plugin is actually how we do start our plugins always, which may explain why we never noticed this behavior before.

The fact that the restart upon receiving an asset and not upon sending the configuration requests to the plugin seems really odd to me, you may want to escalate this at https://github.com/fledge-iot/fledge or https://github.com/fledge-iot/fledge-service-dispatcher level...

**Comment by kwitekrac** [comment]
I have created an issue in the Fledge repository [link](https://github.com/fledge-iot/fledge/issues/1516). Therefore, this issue can now be closed.
