### ISSUE TITLE
Simplifying Set-Point Handling in IEC104 North Plugin

### ISSUE THREAD

**Issue by kwitekrac** [fledge-power/fledge-north-iec104#61]
**Is your feature request related to a problem? Please describe.**

Commands that carry set-point values, such as [C_SC_NA_1](https://infosys.beckhoff.com/content/1033/tf6500_tc3_iec60870_5_10x/984488203.html), initiate communication with an activation command (COT=6). This activation should be acknowledged by the North Plugin through a sequence of COT=7 (activation confirmation) and COT=10 (activation termination) to ensure proper protocol flow and continue communication.

Currently, the implementation forwards the received command directly to the South service by triggering the operation function, adding the command to OutstandingCommands. However, this process skips the necessary acknowledgment steps, implying that the command will only be confirmed after receiving feedback from the South service (see [line 1981](https://github.com/fledge-power/fledge-north-iec104/blob/9f162e1b9d4818b2fc474b695279fcbddd08fafd/src/iec104.cpp#L1981)).

To provide this feedback, the South service needs to update the asset bound to the received command address with the corresponding COT value, which, as I understand it, will trigger the acknowledgment and termination on the IEC104 North Plugin.

This process introduces unnecessary complexity in handling set-point requests. The additional code required to manage these events on the South side will be specific to the IEC104 plugin, meaning the concept of using solutions that are generalizable across protocols is not implemented here.

**Describe the solution you'd like**
I think that if the [forwardCommand](https://github.com/fledge-power/fledge-north-iec104/blob/9f162e1b9d4818b2fc474b695279fcbddd08fafd/src/iec104.cpp#L1974) triggers the `operation` function and it returns true, the command can be confirmed and terminated (at least for Direct commands or when an additional flag is set in plugin config).

**Comment by Aeredren** [comment]
Our point of view about acknowledgement is that acknowledgement must come from the final RTU because when something is acknowledge it mean the RTU is ready to execute the command.

Therefore, acknowledging command to the north when the command is acknowledged southwards is the desire behaviour.
